### ISSUE TITLE
DSUG - 19/09/2020 -  Terraform Workshop by Vamsikrishna Burugadda

### ISSUE THREAD

**Issue by TerraformingCloud** [DSUGHyd/dsughyd-meetups#3]
**Title of the talk/workshop**
Terraform Workshop | Manual deployment | Set up CICD with Github Actions

**Abstract of the talk/workshop**
1. Brief introduction of Terraform
2. Core concepts of Terraform
3. Demo - Deploy a virtual machine in Azure 
4. Set up CICD with Github Actions

**Category of the talk/workshop**
DevOps- Infrastructure as Code

**Duration (including Q&A)**
2 hours

**Level of Audience**
Beginner

**Speaker Bio**
Name : Vamsikrishna Burugadda
Designation : Azure Infrastructure Engineer
Company : Optum, Hyderabad
Email: bvamsi482@gmail.com
Years of Exp : 7
 -->

**Prerequisites(if any)**
Download Terraform (0.13 is preferred) 
Download Visual studio code (Preferred) and Install Terraform Extension
Az CLI (Optional)

**Slides URL**
In progress

**Comment by inovizz** [comment]
@TerraformingCloud - I guess you added duration of the QnA in the issue, ideally it would be 2 hours right?
